# Generated by Django 4.2.4 on 2023-10-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStoreModel',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
                ('first_pub', models.DateTimeField(auto_now_add=True)),
                ('avialabel', models.BooleanField()),
            ],
        ),
    ]
